- name: Deploy hylastix-postgres container
  docker_container:
    name: hylastix-postgres
    image: postgres:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
